# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  resources:
    - resource: Microsoft.PowerToys.Configure/PowerToysConfigure
      directives:
        description: Configure PowerToys
      settings:
        AdvancedPaste:
          Enabled: false
        AlwaysOnTop:
          Enabled: true
          FrameThickness: 5
        Awake:
          Enabled: true
        ColorPicker:
          Enabled: true
        CropAndLock:
          Enabled: true
        EnvironmentVariables:
          Enabled: true
        FancyZones:
          Enabled: false
        FileLocksmith:
          Enabled: true
        ImageResizer:
          Enabled: true
          ImageresizerFallbackEncoder: png
        KeyboardManager:
          Enabled: true
        FindMyMouse:
          Enabled: false
        MouseHighlighter:
          Enabled: false
        MouseJump:
          Enabled: false
        MousePointerCrosshairs:
          Enabled: false
        MouseWithoutBorders:
          Enabled: false
        NewPlus:
          Enabled: false
        Peek:
          Enabled: true
        PowerRename:
          Enabled: true
        PowerLauncher:
          Enabled: false
        PowerAccent:
          Enabled: false
        PowerPreview:
          EnableSvgPreview: true
          EnableSvgThumbnail: true
          EnableMdPreview: true
          EnableMonacoPreview: true
          EnablePdfPreview: true
          EnablePdfThumbnail: false
          EnableGcodePreview: true
          EnableGcodeThumbnail: true
          EnableStlThumbnail: true
          EnableQoiPreview: true
          EnableQoiThumbnail: true
        PowerOcr:
          Enabled: false
        Workspaces:
          Enabled: false
        ShortcutGuide:
          Enabled: true
        MeasureTool:
          Enabled: true
        Hosts:
          Enabled: false
        RegistryPreview:
          Enabled: true
          DefaultRegApp: true

  configurationVersion: 0.2.0
